name: Compile Latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      statuses: read

    steps:
      - uses: actions/checkout@v4
      
      - name: get-zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.13.0
        
      - name: compile
        run: zig build -Doptimize=ReleaseSmall
        
      - name: rename
        run: mv ./zig-out/bin/GameOfLife ./zig-out/bin/GameOfLife-small
        
      - name: compile
        run: zig build -Doptimize=ReleaseFast
        
      - name: "Release"
        uses: "laminas/automatic-releases@v1"
        with:
          command-name: "laminas:automatic-releases:release"
        env:
          "GITHUB_TOKEN": ${{ secrets.ORGANIZATION_ADMIN_TOKEN }}
          "SIGNING_SECRET_KEY": ${{ secrets.SIGNING_SECRET_KEY }}
          "GIT_AUTHOR_NAME": ${{ secrets.GIT_AUTHOR_NAME }}
          "GIT_AUTHOR_EMAIL": ${{ secrets.GIT_AUTHOR_EMAIL }}
          
